CREATE DATABASE DMFINAL
GO

USE DMFINAL
GO

CREATE TABLE [dbo].[DimCLIENTE](
	[SKCLIENTE] [int] IDENTITY(1,1) NOT NULL,
	[ID_CLIENTE][int] null,
	[AP_PATERNO] [varchar](255) null,
	[DOCUMENTO] [varchar](255) null,
	[FECHA_INGRESO] [varchar](255) null,
	[TIPO_CLIENTE] [varchar](255) null,
	[FECNAC] [DATETIME] NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DimPRODUCTO](
	[SKPRODUCTO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO NACIONAL][int] null,
	[NOMBRE_PRODUCTO] [nvarchar](255) null,
	[PRECIO] [float] null,
	[PRECIOIVA] [float] null,
	[STOCK] [int] null
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DimTIENDA](
	[SKTIENDA] [int] IDENTITY(1,1) NOT NULL,
	[ID_TIENDA][int] null,
	[CIUDAD] [nvarchar](255) null,
	[DIRECCION] [nvarchar](255) null,
	[ESTADO_LOCAL] [SMALLINT] null
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DimVENDEDOR](
	[SKVENDEDOR] INT IDENTITY(1,1) NOT NULL,
	[IDVENDEDOR] INT NOT NULL,
	[NOMBRE] [nvarchar](255) NULL,
	[APELLIDO] [nvarchar](255) NULL,
	[TIPO_DOC] [nvarchar](255) NULL,
	[ESTADO_VEND] [SMALLINT] null,
	[TIENDA] [INT] null
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[FactVENTA](
	[SKID] [int] IDENTITY(1,1) NOT NULL,
	[IDVENTA] [int] NULL,
	[PRODUCTO] [int] NULL,
	[FECHA] [DATETIME] NULL,
	[CANTIDAD] [int] NULL,
	[PAGO] [nvarchar](255) NULL,
	[DESCUENTO] FLOAT NULL,
	[CLIENTE] INT NULL,
	[VENDEDOR] INT NULL,
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DimPRODUCTO]
ADD ESTADO_PRODUCTO BIT NULL

TRUNCATE TABLE DimCLIENTE
TRUNCATE TABLE DimPRODUCTO
TRUNCATE TABLE DimTIENDA
TRUNCATE TABLE DimVENDEDOR
TRUNCATE TABLE FactVENTA

SELECT * FROM DimCLIENTE


------PRUEBAS

USE master

IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'STAGINGFINAL')
BEGIN
	CREATE DATABASE [STAGINGFINAL]
END
USE [STAGINGFINAL]

TRUNCATE TABLE CLIENTE
TRUNCATE TABLE PRODUCTO
TRUNCATE TABLE TIENDA
TRUNCATE TABLE VENDEDOR
TRUNCATE TABLE VENTA

SELECT * FROM VENTA
SELECT * FROM CLIENTE
SELECT * FROM TIENDA
SELECT * FROM PRODUCTO
SELECT * FROM VENDEDOR


DROP DATABASE [CLIPRODVT]

DROP DATABASE [DBVENTA]

DROP TABLE [dbo].[Destino de OLE DB]