CREATE DATABASE STAGINGSESION6

GO

USE STAGINGSESION6
GO

TRUNCATE TABLE [dbo].[STGCATEGORIA]
TRUNCATE TABLE [dbo].[STGPRODUCTO]
TRUNCATE TABLE [dbo].[STGTIENDA]
TRUNCATE TABLE [dbo].[STGDETALLEVENTA]
TRUNCATE TABLE [dbo].[STGVENTA]
----------------
SELECT * FROM [dbo].[STGCATEGORIA]
SELECT * FROM [dbo].[STGPRODUCTO]
SELECT * FROM [dbo].[STGTIENDA]
SELECT * FROM [dbo].[STGDETALLEVENTA]
SELECT * FROM [dbo].[STGVENTA]
